// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNiIzGmDDIA9TuvaFdUywJJeozlTrOW14',
    appId: '1:4434856120:web:40c5cc435971e5f013cc4d',
    messagingSenderId: '4434856120',
    projectId: 'digitaldairy-6cf9a',
    authDomain: 'digitaldairy-6cf9a.firebaseapp.com',
    storageBucket: 'digitaldairy-6cf9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDa3ci8t1ky0t4ZnG9YIKBOP2W8Vj0O-c',
    appId: '1:4434856120:android:77eda7b010cc1e5e13cc4d',
    messagingSenderId: '4434856120',
    projectId: 'digitaldairy-6cf9a',
    storageBucket: 'digitaldairy-6cf9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB_0TXjTbzV2iJa1dSOrwP_rg5ms0OA0k',
    appId: '1:4434856120:ios:e43be352bd1c98f513cc4d',
    messagingSenderId: '4434856120',
    projectId: 'digitaldairy-6cf9a',
    storageBucket: 'digitaldairy-6cf9a.firebasestorage.app',
    iosBundleId: 'com.example.digitalDairy',
  );
}
